sometimes main can exit 2
FAIL	github.com/luathn/gotestsum/testjson/internal/badmain	0.001s
ok  	github.com/luathn/gotestsum/testjson/internal/empty	(cached) [no tests to run]
ok  	github.com/luathn/gotestsum/testjson/internal/good	(cached)
FAIL
FAIL	github.com/luathn/gotestsum/testjson/internal/parallelfails	0.020s
FAIL
FAIL	github.com/luathn/gotestsum/testjson/internal/withfails	0.020s
